Cleaning, use proper amount of spaces

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,72 +9,72 @@ dist: trusty
 # Linux - add the Ubuntu restricted tool chain to install GCC 5 and 6, also to
 # install the development package for SDL2
 addons:
-    apt:
-        sources:
-            - ubuntu-toolchain-r-test
-        packages:
-            - libsdl2-dev
-            - linux-libc-dev
-            - gcc-5-multilib
-            - g++-5-multilib
-            - gcc-6-multilib
-            - g++-6-multilib
+  apt:
+    sources:
+    - ubuntu-toolchain-r-test
+    packages:
+    - libsdl2-dev
+    - linux-libc-dev
+    - gcc-5-multilib
+    - g++-5-multilib
+    - gcc-6-multilib
+    - g++-6-multilib
 
 matrix:
-    # If something failed, stop
-    fast_finish: true
-    allow_failures:
-        # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
-        - os: osx
-    include:
-        # Ubuntu 14.04 Trusty Tahr amd64 (Linux) GCC 5
-        - os: linux
-          env: COMPILER=gcc-5
-        # Ubuntu 14.04 Trusty Tahr amd64 (Linux) GCC 6
-        - os: linux
-          env: COMPILER=gcc-6
-        # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
-        - os: osx
+  # If something failed, stop
+  fast_finish: true
+  allow_failures:
+    # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
+      - os: osx
+  include:
+    # Ubuntu 14.04 Trusty Tahr amd64 (Linux) GCC 5
+    - os: linux
+      env: COMPILER=gcc-5
+    # Ubuntu 14.04 Trusty Tahr amd64 (Linux) GCC 6
+    - os: linux
+      env: COMPILER=gcc-6
+    # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
+    - os: osx
 
 before_install:
-    - |
-      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-        sudo dpkg --add-architecture i386
-        sudo apt-get -qq update
-        sudo apt-get install -y linux-libc-dev:i386
-      fi
+  - |
+    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+      sudo dpkg --add-architecture i386
+      sudo apt-get -qq update
+      sudo apt-get install -y linux-libc-dev:i386
+    fi
 
 install:
-    # Prepare the dependencies, build and fake Steam common directories for Travis
-    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
-    - STEAMCOMMON_DIR="${TRAVIS_BUILD_DIR}/steam_common"
-    - mkdir -p ${DEPS_DIR} && mkdir -p ${STEAMCOMMON_DIR} && mkdir -p ${STEAMCOMMON_DIR} && cd ${DEPS_DIR}
-    # Get the latest CMake version
-    - |
-      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-        CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz"
-        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
-        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
-      else
-        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
-      fi
+  # Prepare the dependencies, build and fake Steam common directories for Travis
+  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
+  - STEAMCOMMON_DIR="${TRAVIS_BUILD_DIR}/steam_common"
+  - mkdir -p ${DEPS_DIR} && mkdir -p ${STEAMCOMMON_DIR} && mkdir -p ${STEAMCOMMON_DIR} && cd ${DEPS_DIR}
+  # Get the latest CMake version
+  - |
+    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz"
+      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
+      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
+    else
+      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
+    fi
 
 before_script:
-    # Move to build directory
-    - cd ${TRAVIS_BUILD_DIR}
-    - mkdir build && cd build
+  # Move to build directory
+  - cd ${TRAVIS_BUILD_DIR}
+  - mkdir build && cd build
 
 script:
-    # Just execute the cmake and make commands
-    - |
-      if [[ "${COMPILER}" == "gcc-5" ]]; then
-        cmake -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_C_COMPILER="gcc-5" -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.so.0 -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.so ..
-      elif [[ "${COMPILER}" == "gcc-6" ]]; then
-        cmake -DCMAKE_CXX_COMPILER="g++-6" -DCMAKE_C_COMPILER="gcc-6" -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.so.0 -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.so ..
-      else
-        cmake -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.0.dylib -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.dylib ..
-      fi
-    - make
+  # Just execute the cmake and make commands
+  - |
+    if [[ "${COMPILER}" == "gcc-5" ]]; then
+      cmake -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_C_COMPILER="gcc-5" -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.so.0 -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.so ..
+    elif [[ "${COMPILER}" == "gcc-6" ]]; then
+      cmake -DCMAKE_CXX_COMPILER="g++-6" -DCMAKE_C_COMPILER="gcc-6" -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.so.0 -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.so ..
+    else
+      cmake -DSTEAMCOMMON=${STEAMCOMMON_DIR} -DSDL2=${TRAVIS_BUILD_DIR}/external/SDL2/lib/libSDL2-2.0.0.dylib -DVGUI1=${TRAVIS_BUILD_DIR}/lib/public/vgui.dylib ..
+    fi
+  - make
 
 notifications:
   email: false
